/*
 * ComponentSerialize.h
 * Generated from generator_in_files/ComponentSerialize.h.in
 * This file should be automatically generated by the python script
 * generate_component_names.py. It defines Serializers for every
 * component, implementation in the associated .cpp file
 */
#ifndef SRC_COMPONENTSERIALIZE_H_
#define SRC_COMPONENTSERIALIZE_H_

#include "IncludeJson.hpp"
#include "IncludeComponents.hpp"

void from_json(const json&, Hill&);
void to_json(json&, const Hill&);
void from_json(const json&, Water&);
void to_json(json&, const Water&);
void from_json(const json&, Bat&);
void to_json(json&, const Bat&);
void from_json(const json&, Child&);
void to_json(json&, const Child&);
void from_json(const json&, Parent&);
void to_json(json&, const Parent&);
void from_json(const json&, DroneSound&);
void to_json(json&, const DroneSound&);
void from_json(const json&, HoverSound&);
void to_json(json&, const HoverSound&);
void from_json(const json&, WorldVel&);
void to_json(json&, const WorldVel&);
void from_json(const json&, WorldPos&);
void to_json(json&, const WorldPos&);
void from_json(const json&, SpriteMulti&);
void to_json(json&, const SpriteMulti&);
void from_json(const json&, SpriteSizeRot&);
void to_json(json&, const SpriteSizeRot&);
void from_json(const json&, SpriteQuad&);
void to_json(json&, const SpriteQuad&);
void from_json(const json&, SpriteAnim&);
void to_json(json&, const SpriteAnim&);
void from_json(const json&, ScreenPos&);
void to_json(json&, const ScreenPos&);
void from_json(const json&, LevelObj&);
void to_json(json&, const LevelObj&);
void from_json(const json&, HitBox&);
void to_json(json&, const HitBox&);

#endif /* SRC_COMPONENTSERIALIZE_H_ */
