/*
 * ComponentList.h
 * This file should be automatically generated by the python script
 * generate_component_names.py
 */

#ifndef SRC_COMPONENTLIST_H_
#define SRC_COMPONENTLIST_H_

#include "components/WorldPos.h"
#include "components/SpriteAnim.h"
#include "components/SpriteSizeRot.h"
#include "components/SpriteQuad.h"
#include "components/ScreenPos.h"

#endif /* SRC_COMPONENTLIST_H_ */
