/*
 * ComponentSerialize.cpp
 *
 *  Created on: Jul 23, 2020
 *      Author: rei de vries
 */

#ifndef SRC_COMPONENTSERIALIZE_CPP_
#define SRC_COMPONENTSERIALIZE_CPP_

#include "ComponentSerialize.hpp"

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(AllBatSounds, stub)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Hill, occupied)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Water, occupied)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Bat, stamina, water)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Child, name)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Parent, name)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(DroneSound, sound)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(HoverSound, sound)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(WorldVel, vel, impulse, impulse_fall_rate)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(WorldPos, pos)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(SpriteMulti, sprites, pos, visible)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(SpriteSizeRot, size, rot)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(SpriteQuad, quad)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(SpriteAnim, sprite, show, anim_speed)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(ScreenPos, pos)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(LevelObj, name)
NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(HitBox, box)

#endif /* SRC_COMPONENTSERIALIZE_H_ */
