/*
 * ComponentList.h
 * This file should be automatically generated by the python script
 * generate_component_names.py
 */


#include "components/WorldPos.h"
#include "components/SpriteAnim.h"
#include "components/SpriteSizeRot.h"
#include "components/SpriteQuad.h"
#include "components/ScreenPos.h"

