/*
 * ComponentNames.h
 * This file should be automatically generated by the python script
 * generate_component_names.py
 */

#ifndef SRC_COMPONENTNAMES_H_
#define SRC_COMPONENTNAMES_H_

#include <string>

namespace Cat
{
	int NUM_COMPONENT_TYPES = 5;

	std::string component_names = {
		"WorldPos",
		"SpriteAnim",
		"SpriteSizeRot",
		"SpriteQuad",
		"ScreenPos",
	};

	enum ComponentType {
		WorldPos,
		SpriteAnim,
		SpriteSizeRot,
		SpriteQuad,
		ScreenPos,
	};
}

#endif /* SRC_COMPONENTNAMES_H_ */
