/*
 * ComponentIncludes.h
 * Generated from generator_in_files/ComponentIncludes.h.in
 * This file should be automatically generated by the python script
 * generate_component_names.py. It contains includes for every
 * component.
 */

#include "components/WorldPos.h"
#include "components/SpriteSizeRot.h"
#include "components/SpriteQuad.h"
#include "components/SpriteAnim.h"
#include "components/ScreenPos.h"
#include "components/LevelID.h"
