/*
 * IncludeComponents.hpp
 * Generated from generator_in_files/IncludeComponents.hpp.in
 * This file should be automatically generated by the python script
 * generate_component_names.py. It contains includes for every
 * component.
 */

#include "components/AllBatSounds.hpp"
#include "components/Hill.hpp"
#include "components/Water.hpp"
#include "components/Bat.hpp"
#include "components/Child.hpp"
#include "components/Parent.hpp"
#include "components/DroneSound.hpp"
#include "components/HoverSound.hpp"
#include "components/WorldVel.hpp"
#include "components/WorldPos.hpp"
#include "components/SpriteMulti.hpp"
#include "components/SpriteSizeRot.hpp"
#include "components/SpriteQuad.hpp"
#include "components/SpriteAnim.hpp"
#include "components/ScreenPos.hpp"
#include "components/LevelObj.hpp"
#include "components/HitBox.hpp"
