/*
 * IncludeComponents.hpp
 * Generated from generator_in_files/IncludeComponents.hpp.in
 * This file should be automatically generated by the python script
 * generate_component_names.py. It contains includes for every
 * component.
 */

#include "components/HoverSound.hpp"
#include "components/WorldPos.hpp"
#include "components/SpriteSizeRot.hpp"
#include "components/SpriteQuad.hpp"
#include "components/SpriteAnim.hpp"
#include "components/ScreenPos.hpp"
#include "components/LevelID.hpp"
#include "components/HitBox.hpp"
